# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "de52f520dfe13b84f9ff34d1fd8a32c5"
name = "volume-discount"
handle = "volume-discount-92"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
dev_store_url = "demo-arpit.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_discounts,write_discounts_allocator_functions,write_products"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2025-01"

[pos]
embedded = false
